# =================================================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================================================

spring:
    datasource:
        initialization-mode: never
        hikari:
            auto-commit: false
    profiles:
        active: jdbc
