INSERT INTO USER(USERNAME, PASSWORD) VALUES ('admin', '{PLAIN}pw');	
INSERT INTO USER(USERNAME, PASSWORD) VALUES ('user', '{PLAIN}pw');
	
	
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES ('admin',	'ROLE_ADMIN');
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES ('admin',	'ROLE_USER');	
INSERT INTO AUTHORITY(USERNAME, ROLE) VALUES ('user', 'ROLE_USER');		
