DROP TABLE IF EXISTS OAUTH_CLIENT_DETAILS CASCADE;


CREATE TABLE OAUTH_CLIENT_DETAILS (
	CLIENT_ID				VARCHAR(255) NOT NULL,
	RESOURCE_IDS			VARCHAR(255),
	CLIENT_SECRET			VARCHAR(255),
	SCOPE					VARCHAR(255),
	AUTHORIZED_GRANT_TYPES	VARCHAR(255),
	WEB_SERVER_REDIRECT_URI	VARCHAR(255),
	AUTHORITIES				VARCHAR(255),
	ACCESS_TOKEN_VALIDITY	INTEGER,
	REFRESH_TOKEN_VALIDITY	INTEGER,
	ADDITIONAL_INFORMATION	VARCHAR(4096),
	AUTOAPPROVE				VARCHAR(255)
);
ALTER TABLE OAUTH_CLIENT_DETAILS ADD CONSTRAINT OAUTH_CLIENT_DETAILS_PK PRIMARY KEY (CLIENT_ID);
COMMENT ON TABLE OAUTH_CLIENT_DETAILS IS 'Tabelle für OAUTH_CLIENT_DETAILS';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_ID IS 'Primary Key';
