DROP TABLE IF EXISTS OAUTH_CODE CASCADE;


--LONGVARBINARY
CREATE TABLE OAUTH_CODE (
	CODE			VARCHAR(255),
	AUTHENTICATION	VARBINARY(4096)
);
CREATE INDEX OAUTH_CODE_IDX_CODE ON OAUTH_CODE (CODE);
COMMENT ON TABLE OAUTH_CODE IS 'Tabelle für OAUTH_CODE';
COMMENT ON COLUMN OAUTH_CODE.CODE IS 'CODE';
