DROP TABLE IF EXISTS OAUTH_APPROVALS CASCADE;

CREATE TABLE OAUTH_APPROVALS (
	USERID			VARCHAR(255),
	CLIENTID		VARCHAR(255),
	SCOPE			VARCHAR(255),
	STATUS			VARCHAR(10),
	EXPIRESAT		TIMESTAMP,
	LASTMODIFIEDAT	TIMESTAMP
);

CREATE INDEX OAUTH_APPROVALS_IDX_USERID ON OAUTH_APPROVALS (USERID);
CREATE INDEX OAUTH_APPROVALS_IDX_CLIENTID ON OAUTH_APPROVALS (CLIENTID);
CREATE INDEX OAUTH_APPROVALS_IDX_SCOPE ON OAUTH_APPROVALS (SCOPE);

COMMENT ON TABLE OAUTH_APPROVALS IS 'Tabelle für OAUTH_APPROVALS';
COMMENT ON COLUMN OAUTH_APPROVALS.USERID IS 'USERID';