# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    boot:
        admin:
            client:
                enabled: true
                instance:
                    prefer-ip: true
                url: ${ADMIN_SERVER:http://localhost:9000}
    cloud:
        config:
            enabled: false
        gateway:
            enabled: true
            metrics:
                enabled: true
            routes:

                -   id: addrequestheader_route
                    # Demo für httpbin.org
                    uri: http://httpbin.org:80
                    predicates:
                        - Path=/get
                    filters:
                        - AddRequestHeader=Hello, World
                        -
                -   id: circuitbreaker_route
                    uri: http://httpbin.org:80
                    predicates:
                        - Host=*.circuitbreaker.com
                    filters:
                        -   name: circuitbreaker
                            args:
                                name: mycmd
                                fallbackUri: forward:/fallback

                -   id: rewritepath_route
                    # Einfache Weiterleitung
                    uri: "http://localhost:8081"
                    predicates:
                        - Path=/hello
                    filters:
                        - RewritePath="/hello(?<segment>/?.*)", "/${segment}"

                -   id: loadbalancer_eureka
                    # Eureka LoadBalancer, nur wenn ribbon.eureka.enabled = true
                    # /sysdatelb/service/sysdate -> /service/sysdate
                    uri: lb://HELLO-SERVICE
                    predicates:
                        - Path=/lb/**
                    filters:
                        - StripPrefix=1

                -   id: loadbalancer_manuell
                    # Manueller LoadBalancer, nur wenn ribbon.eureka.enabled = false
                    uri: lb://HELLO-SERVICE-MANUELL
                    predicates:
                        - Path=/lbman
                    filters:
                        - RewritePath=/lbman, /
