# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        register-with-eureka: false
        serviceUrl:
            defaultZone: \${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}

logging:
    level:
        root: INFO
        org.springframework: INFO

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
                #include: health, gateway
    endpoint:
        gateway:
            enabled: true
        health:
            enabled: true
            show-details: ALWAYS

server:
    port: 8091

spring:
    application:
        name: cloud-api-gateway
    boot:
        admin:
            client:
                enabled: true
                url: \${ADMIN_SERVER:http://localhost:9000}
    cloud:
        loadbalancer:
            health-check:
                interval: 5s
            cache:
                ttl: 10s
            retry:
                enabled: true
                max-retries-on-next-service-instance: 2
                max-retries-on-same-service-instance: 2
            ribbon:
                enabled: false

---

spring:
    boot:
        admin:
            client:
                enabled: false
    config:
        activate:
            on-profile: test

eureka:
    client:
        enabled: false
