# docker network create my-fancy-network
# docker run -i -t --name container1 --net=my-fancy-network --net-alias=container1 ubuntu:trusty /bin/bash
# docker run -i -t --name container2 --net=my-fancy-network --net-alias=container2 ubuntu:trusty /bin/bash
# Die Container können sich nun untereinander über ihre Aliasnamen ansprechen (HTTP://container1), keine IPs verwenden !

# docker-compose build
# docker-compose up [-d] --scale spring-microservice=3
# docker-compose ps
# docker logs ID/NAME;
# docker-compose down

version: '3'
services:

    spring-admin:
        container_name: spring-admin
        build:
            context: ./spring-boot-admin
            dockerfile: Dockerfile
        image: spring-admin:latest
        restart: always
        environment:
            SPRING_APPLICATION_JSON:
                '{
         "spring":
         {
           "boot":
           {
             "client":
             {
               "prefer-ip": "true"
             }
           }
         }
       }'
        ports:
            - 9000:9000
        networks:
            main:
                aliases:
                    - admin

    spring-eureka:
        container_name: spring-eureka
        build:
            context: ./spring-eureka
            dockerfile: Dockerfile
        image: spring-eureka:latest
        restart: always
        environment:
            SPRING_APPLICATION_JSON:
                '{
         "eureka":
         {
           "client":
           {
             "serviceUrl":
             {
               "defaultZone": "http://eureka:9001/eureka"
             }
           }
         }
       }'
        ports:
            - 9001:9001
        networks:
            main:
                aliases:
                    - eureka

    spring-microservice:
        #container_name: spring-microservice
        build:
            context: ./spring-microservice
            dockerfile: Dockerfile
        image: spring-microservice:latest
        restart: always
        environment:
            SPRING_APPLICATION_JSON:
                '{
        "eureka":
        {
          "client":
          {
            "serviceUrl":
            {
              "defaultZone": "http://eureka:9001/eureka"
            }
          },
          "instance":
          {
            "preferIpAddress": "true"
          }
        },
        "server":
        {
          "port": "9999"
        },
        "spring":
        {
          "boot":
          {
            "admin":
            {
              "client":
              {
                "instance":
                {
                  "prefer-ip": "true"
                },   
                "url": "http://admin:9000"
              }
            }
          }
        }
       }'
            #- JAVA_OPTS="-Dserver.port=0"
            #expose:
            #- 8081
            #ports:
            #- 8081
        depends_on:
            - spring-admin
            - spring-eureka
            #links:
            #- admin:spring-admin
            #- eureka:spring-eureka
        networks:
            main:

    spring-microservice_a:
        container_name: spring-microservice_a
        build:
            context: ./spring-microservice
            dockerfile: Dockerfile
        image: spring-microservice:latest
        restart: always
        environment:
            SPRING_APPLICATION_JSON:
                '{
        "eureka":
        {
          "client":
          {
            "serviceUrl":
            {
              "defaultZone": "http://eureka:9001/eureka"
            }
          },
          "instance":
          {
            "preferIpAddress": "true"
          }
        },
        "server":
        {
          "port": "8888"
        },
        "spring":
        {
          "boot":
          {
            "admin":
            {
              "client":
              {
                "instance":
                {
                  "prefer-ip": "true"
                },   
                "url": "http://admin:9000"
              }
            }
          }
        }
       }'
        ports:
            - 8081:8888
        depends_on:
            - spring-admin
            - spring-eureka
        networks:
            main:
                aliases:
                    - service_a


#  loadbalancer:
#    container_name: spring-haproxy
#    image: dockercloud/haproxy:latest
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 8080:8081
#    networks:
#      - main
#    links:
#      - microservice
#
#
# Network-Bridge: Zugriff auf Services die auf dem Host 192.168.155.1 laufen.
# docker network create -d bridge --subnet 192.168.155.0/24 --gateway 192.168.155.1 dockernet;
# docker network rm dockernet;
#
# localhost im Docker-Netz finden: ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1;
networks:
    main:
    #default:
    #driver: bridge
    #dockernet:
    #external: true
