logging:
   level:
      org.springframework: INFO
      org.springframework.security.oauth2: DEBUG
    
server:
   port: 8083
   http2:
      enabled: true    
   servlet:
      context-path: /
   error:
      whitelabel:
         enabled: false
 
 
security:
   oauth2:
      client:
         clientId: OrdixSampleID
         clientSecret: ordixSecret
         accessTokenUri: http://localhost:8081/auth/oauth/token
         userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      resource:
         userInfoUri: http://localhost:8081/auth/user/me
         token-info-uri: http://localhost:8081/auth/oauth/check_token


   
   