logging:
    pattern:
        console: "%date{HH:mm:ss.SSS} - %clr(%5level) - [%30.-30thread] - %clr(%-40.-40logger{0}){magenta} - %message%n"
    level:
        org.springframework: INFO

#server:
#    port: 8081
#    servlet:
#        context-path: /
#    shutdown: graceful

spring:
    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: jdbc:h2:mem:jooq;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        #        url: jdbc:h2:file:./databases/h2/jooq
        driver-class-name: org.h2.Driver
        username: sa
        password:
    #    profiles:
    #        active: memory
    sql:
        init:
            mode: embedded
            #    h2:
            #        console:
            #            enabled: true
            #            path: /h2-console
            #settings.trace: false
            #settings.web-allow-others: false
