# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

logging:
    pattern:
        console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS

server:
    http2:
        enabled: true
    port: 8090
