# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

logging:
    pattern:
        console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS

server:
    http2:
        enabled: true
    port: 8090

spring:
    datasource:
        #url: ${DB_URL:jdbc:hsqldb:hsql://${DB_HOST}:${DB_PORT}/memDb}
        url: ${DB_URL:jdbc:h2:tcp://${DB_HOST}:${DB_PORT}/file:fileDb}
        username: ${DB_USER}
        password: ${DB_PSW}
        hikari:
            auto-commit: true
            minimum-idle: 1
            maximum-pool-size: 3

#    r2dbc:
#        #url: ${R2DBC_URL:r2dbc:h2:tcp://${DB_HOST}:${DB_PORT}/mem:memDb}
#        #url: ${R2DBC_URL:r2dbc:h2:mem:///memDb?DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=true}
#        username: sa
#        password:
#        pool:
#            enabled: true
#            min-idle: 1
#            max-size: 3
