# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# ===================================================================

logging:
    level:
        root: OFF
        ch.qos.logback: OFF
        org.springframework.*: OFF
        de.freese: INFO
        reactor: INFO

spring:
    main:
        #banner-mode: OFF
        web-application-type: NONE
    rsocket:
        server:
            address: localhost
            port: 7000
            transport: TCP
