# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

pattern:
   logback:
      console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"
      file: "%date{yyyy-MM-dd HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"
   log4j2:
      console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace{%-40.-40logger{0}}{ }{.} - %message%n"
      file: "%date{yyyy-MM-dd HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace{%-40.-40logger{0}}{ }{.} - %message%n"
   
logging:
#  config: classpath:logback-default.xml
#  config: classpath:log4j-default.xml 
   level:
      root: INFO
      org.springframework: INFO
   path: ${user.dir}/logs # -> logging.path    
   #file: ${logging.path}/application.log # ist nicht zulässig in YAML, siehe Workaround im Profile.
   file:
      max-history: 30
      max-size: 10MB         
   pattern:
      console: ${pattern.logback.console}
      file: ${pattern.logback.file}
   register-shutdown-hook: false       

spring:
   main:
      lazy-initialisation: false
       
---

spring:
   profiles: producer
   main:
      web-application-type: NONE     
   rsocket:
      server:
         port: 7000

# Workaround         
logging:
   file: ${logging.path}/producer.log  
   
---

spring:
   profiles: consumer
   
server:
   http2:
      enabled: true 
   port: 8080

# Workaround     
logging:
   file: ${logging.path}/consumer.log     
       