# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# ===================================================================

pattern:
   logback:
      console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"
      file: "%date{yyyy-MM-dd HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"
   log4j2:
      console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace{%-40.-40logger{0}}{ }{.} - %message%n"
      file: "%date{yyyy-MM-dd HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace{%-40.-40logger{0}}{ }{.} - %message%n"
   
logging:
#  config: classpath:logback-default.xml
#  config: classpath:log4j-default.xml 
   level:
      root: INFO
      org.springframework: INFO   
      io.rsocket.FrameLogger: DEBUG
   file:
      #path: ${user.dir}/logs
      #path: /tmp/logs   
      max-history: 30
      max-size: 10MB
      total-size-cap: 1GB
   pattern:
      console: ${pattern.logback.console}
      file: ${pattern.logback.file}
   register-shutdown-hook: false       

---

spring:
   profiles: server
   main:
      web-application-type: NONE     
   rsocket:
      server:
         address: localhost
         port: 7000
         transport: TCP
        
logging:
   file:
      name: logs/server.log
        
---

spring:
   profiles: client
    
logging:
   file:
      name: logs/client.log 
          
server:
   http2:
      enabled: true 
   port: 8080
   
rsocket:
   server:
      address: localhost
      port: 7000  
 