plugins {
    id("java")
    id("org.springframework.boot")
}

description = "spring-ai example"

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.ai:spring-ai-starter-model-openai")
    // implementation("org.springframework.ai:spring-ai-starter-model-anthropic")
}

springBoot {
    mainClass = "de.spring.ai.simple.GithubApplication"
}

bootRun {
    systemProperty("openai.logging", "body")
}