# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}

logging:
    #level:
    #root: INFO
    #org.springframework: INFO
    pattern:
        console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            enabled: true
            show-details: ALWAYS

server:
    port: 8888
    #servlet:
    #context-path: /

spring:
    application:
        name: hello-service
    boot:
        admin:
            client:
                enabled: true
                instance:
                    prefer-ip: true
                url: ${ADMIN_SERVER:http://localhost:9000}

---

eureka:
    client:
        enabled: false

spring:
    boot:
        admin:
            client:
                enabled: false
    profiles: test
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss"
        deserialization:
            ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT: false
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: false
            FAIL_ON_UNKNOWN_PROPERTIES: false
            FAIL_ON_NULL_FOR_PRIMITIVES: true
            UNWRAP_ROOT_VALUE: false
        locale: de_DE
        property-naming-strategy: SNAKE_CASE
        serialization:
            INDENT_OUTPUT: true
            WRAP_ROOT_VALUE: false
            WRITE_DATES_AS_TIMESTAMPS: false
            WRITE_DATES_WITH_ZONE_ID: false
        time-zone: Europe/Berlin
    main:
        banner-mode: "OFF"
    mvc:
        locale: de_DE
        throw-exception-if-no-handler-found: true
    output:
        ansi:
            enabled: DETECT   
