# =================================================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================================================
logging:
    level:
        root: INFO
        org.springframework: INFO

server:
    port: 8080
    #servlet:
    #    context-path: /openapi


springdoc:
    api-docs:
        path: /api-docs
    #default-produces-media-type: application/json
    swagger-ui:
        #    path: /swagger-ui-custom.html
        displayRequestDuration: true
        filter: true
        operationsSorter: method
        tagsSorter: alpha
        tryItOutEnabled: true
