# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
# ===================================================================

spring:
  application:
    name: webflux-demo
  main:
    banner-mode: "OFF"
    web-environment: false
    web-application-type: NONE

logging:
  level:
    de.freese.j2ee.spring.webflux: DEBUG

---

spring:
  profiles: development

loadbalancer:
  servers: localhost:55501,localhost:55502,localhost:55503

---

spring:
  profiles: production

loadbalancer:
  servers: localhost:45501,localhost:45502,localhost:45503





