# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# ===================================================================
  
rsocket:
   server:
      #address: localhost siehe RSocketClient.login
      #port: 7000  
 