# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
# ===================================================================

# Sich selbst nirgendwo als Client registrieren (No Replication, Standalone Mode).
eureka:
  client:
    fetchRegistry: false
    #lease:
      #duration: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: eureka
    #leaseRenewalIntervalInSeconds: 10
    #leaseExpirationDurationInSeconds: 20
    healthCheckUrlPath: health
    statusPageUrlPath: info
  server:
    #renewalPercentThreshold: 0.5
    enableSelfPreservation: true
    #waitTimeInMsWhenSyncEmpty: 0    
        
server:
  port: 9001
  #servlet:
    #context-path: /eureka
    
spring:
   jmx:
      enabled: false    
