# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
# ===================================================================

eureka:
    client:
        fetchRegistry: false  
        registerWithEureka: true
        
server:
    port: 8761
    #servlet:
        #context-path: /eureka
    
info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}  

---

spring:
    profiles: detailed
   
eureka:
    client:
        #lease:
            #duration: 5
        # Sich selbst nirgendwo als Client registrieren (No Replication, Standalone Mode).  
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    instance:
        hostname: eureka
        #leaseRenewalIntervalInSeconds: 10
        #leaseExpirationDurationInSeconds: 20
        healthCheckUrlPath: health
        statusPageUrlPath: info
    server:
        #renewalPercentThreshold: 0.5
        enableSelfPreservation: true
        #waitTimeInMsWhenSyncEmpty: 0


    