# =================================================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================================================


# =================================================================================================
# Application Properties


# =================================================================================================
# Spring Properties
logging:
   level:
      org.springframework: INFO
      org.springframework.security.oauth2: DEBUG
    
spring:
   flyway:
      #baseline-on-migrate: true  
      enabled: true
      encoding: UTF-8
      locations: classpath:db/hsqldb
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:hsqldb:file:db/hsqldb/oauth;create=true;shutdown=true
      #url: jdbc:hsqldb:mem:oauth;create=true;shutdown=true
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      username: sa
      password: 
      hikari:
         connection-test-query: select 1 from INFORMATION_SCHEMA.SYSTEM_USERS  
         maximum-pool-size: 1
         minimum-idle: 3
         connection-timeout: 5000 
         auto-commit: true
         read-only: false
         validation-timeout: 3000
         idle-timeout: 60000
   jmx:
      enabled: false      
   mvc:
      throw-exception-if-no-handler-found: true
   resources:
      add-mappings: false      

# =================================================================================================
# Server Properties
server:
   port: 8081
   servlet:
      context-path: /auth
   error:
      whitelabel:
         enabled: false       


