# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: false
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true
        
gateway:
    remoteUri: http://httpbin.org:80  
    server1: ${MICRO_SERVICE:localhost:8081}
    servers: ${gateway.server1}, localhost:8082, localhost:8083
    
info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}    

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
                #include: health, gateway
    endpoint:
        gateway:
            enabled: true
        health:
            enabled: true
            show-details: ALWAYS
            
server:
   port: 9999
   
spring:
    application:
        name: gateway-demo
    boot:
        admin:
            client:
                enabled: true
                instance:
                   prefer-ip: true
                url: ${ADMIN_SERVER:http://localhost:9000}
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
            health-check:
                interval: 5s
        #discovery:
        #    client:
        #        simple:
        #            instances:
        #                DATE-SERVICE-MANUELL:
        #                  - URI: http://localhost:8081
        #                  - URI: http://localhost:8082
        #                  - URI: http://localhost:8083
        # HealthCheck Konfiguration ???           

---

spring:
    boot:
        admin:
            client:
                enabled: false 
    profiles: test                       

eureka:
    client:
        enabled: false
        
ribbon:
    eureka:
        enabled: false
              
