# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
# ===================================================================

eureka:
    client:
        fetchRegistry: false
        register-with-eureka: false
        region: eu-west-1

info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            enabled: true
            show-details: ALWAYS

server:
    port: 8761
    #servlet:
    #context-path: /eureka

spring:
    application:
        name: cloud-eureka-server
    boot:
        admin:
            client:
                enabled: true
                url: ${ADMIN_SERVER:http://localhost:9000}
