logging:
   level:
      org.springframework: INFO
      org.springframework.security.oauth2: DEBUG
      
server:
   port: 8082
   error:
      whitelabel:
         enabled: true   
   http2:
      enabled: true     
   session:
      cookie:
         name: UISESSION
         
spring:
   thymeleaf:
      cache: false
   security:
      oauth2:
         client:
            registration:
               custom-client:
                  client-id: my-client-id-read
                  client-secret: my-client-secret
                  client-name: My Auth Server
                  scope: user_info
                  provider: custom-provider
                  redirect-uri: http://localhost:8082/login/oauth2/code/
                  client-authentication-method: basic
                  authorization-grant-type: authorization_code
            provider:
               custom-provider:
                  token-uri: http://localhost:8081/auth/oauth/token
                  authorization-uri: http://localhost:8081/auth/oauth/authorize
                  user-info-uri: http://localhost:8081/auth/user/me
                  user-name-attribute: name

