logging:
    pattern:
        console: "%date{HH:mm:ss.SSS} - %clr(%5level) - [%30.-30thread] - %clr(%-40.-40logger{0}){magenta} - %message%n"
    level:
        org.springframework: INFO
        org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
        de.spring.ai: DEBUG

info:
    app:
        description: @project_description@
        name: @project_artifactId@
        version: @project_version@

server:
    port: 8081
    servlet:
        context-path: /
    shutdown: graceful

spring:
    config:
        import: "optional:file:${user.home}/.spring_env[.properties]"
    output:
        ansi:
            #enabled: DETECT
            enabled: ALWAYS
            #enabled: NEVER
    ai:
        #ollama:
        #    base-url: http://localhost:11434
        #    chat:
        #        # model: mixtral:8x7B
        #        # model: mistral-nemo:12b
        #        model: llama3.2
        #
        #        # Temperature controls the randomness or "creativity" of the model's response.
        #        temperature: 0.5
        #
        #        # Limits token selection to the K most likely next tokens.
        #        # Higher values (e.g., 40-50) introduce more diversity.
        #        topK: 40
        #
        #        # (nucleus sampling): Dynamically selects from the smallest set of tokens whose cumulative probability exceeds P.
        #        # Values like 0.8-0.95 are common.
        #        topP: 0.8
        #
        #        # The maxTokens parameter limits how many tokens (word pieces) the model can generate in its response.
        #        maxTokens: 1024
        #    embedding:
        #        options:
        #            model: snowflake-arctic-embed2
        #            num-ctx: 8192
        openai:
            api-key: ${AI_API_KEY}
            base-url: ${AI_BASE_URL}
            chat:
                model: gpt-4o-mini

                # Temperature controls the randomness or "creativity" of the model's response.
                # Low (0.0 - 0.5): The model sticks to the most statistically likely words, producing deterministic, focused, and reliable output.
                # Medium (0.5 - 1.0): Strikes a balance, allowing for some variation while remaining coherent, good for general tasks like coding or business writing.
                # High (1.0+): Explores less probable words, leading to diverse, creative, and sometimes unexpected or nonsensical results, great for brainstorming or fiction.
                # No support in gpt-5.x
                temperature: 0.75

                # Not supported by all Models.
                #temperature: 1

                # Not supported by all Models.
                # Limits token selection to the K most likely next tokens.
                # Higher values (40-50) introduce more diversity.
                # topK: 40

                # (nucleus sampling): Dynamically selects from the smallest set of tokens whose cumulative probability exceeds P.
                # Values like 0.8-0.95 are common.
                topP: 0.8

                # The maxTokens parameter limits how many tokens (word pieces) the model can generate in its response.
                #maxTokens: 1024
            embedding:
                options:
                    model: text-embedding-3-large

                    # Numbers in Embedding-Vector.
                    # Common: 1024
                    # Max. 3072
                    dimensions: 3072
            image:
                options:
                    model: gpt-image-1

                    # Output format depends on the Model.
                    # Default for gpt-image-1: PNG

                    # Depends on the Model.
                    # auto
                    # 1536x1024
                    # 1024x1536
                    # 1024x1024
                    # 512x512
                    size: 1024x1024

                    # Not supported by all Models.
                    # vivid: hyper-realistic and dramatic images
                    # natural: more natural and less hyper-realistic images
                    #style: natural

                    # Depends on the Model.
                    # auto
                    # low
                    # medium
                    # high
                    # standard
                    # hd
                    quality: medium

                    # Not supported by all Models.
                    # url: The generated image will be accessible via a URL of 60-minute validity.
                    # b64_json: Receive the image as a Base64-encoded string.
                    #response-format: b64_json

    datasource:
        url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    profiles:
        active: memory
    sql:
        init:
            mode: ALWAYS
    h2:
        console:
            enabled: true
            path: /h2-console
            #settings.trace: false
            #settings.web-allow-others: false
