# docker network create my-fancy-network
# docker run -i -t --name container1 --net=my-fancy-network --net-alias=container1 ubuntu:trusty /bin/bash
# docker run -i -t --name container2 --net=my-fancy-network --net-alias=container2 ubuntu:trusty /bin/bash
# Die Container können sich nun untereinander über ihre Aliasnamen ansprechen (HTTP://container1), keine IPs verwenden !

# docker-compose build;
# docker-compose up --build;
# docker-compose up -d --scale spring-cloud-microservice=3;
# docker-compose ps;
# docker logs ID/NAME;
# docker-compose down

# for i in {1..1000}; do curl localhost/service/sysdate; echo ""; sleep 1; done;
#
# multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/
# https://github.com/benwilcock/spring-cloud-gateway-demo

version: '3'
services:

    spring-cloud-boot-admin:
        container_name: spring-cloud-boot-admin
        build:
            context: ./spring-cloud-boot-admin
            dockerfile: Dockerfile
        image: spring-cloud-boot-admin:latest
        ports:
            - 9000:9000
        restart: unless-stopped                                   

    spring-cloud-eureka:
        container_name: spring-cloud-eureka
        build:
            context: ./spring-cloud-eureka
            dockerfile: Dockerfile
        image: spring-cloud-eureka:latests
        ports:
            - 8761:8761
        restart: unless-stopped                          

    spring-cloud-microservice:
        # Kein 'container_name' möglich wegen Scaling: docker-compose up -d --scale spring-cloud-microservice=3
        build:
            context: ./spring-cloud-microservice
            dockerfile: Dockerfile
        image: spring-cloud-microservice:latest
        environment:
            - VM_PARAMS=
                -Xms64m
                -Xmx256m
                -DEUREKA_SERVER=http://spring-cloud-eureka:8761/eureka
                -DADMIN_SERVER=http://spring-cloud-boot-admin:9000              
        depends_on:
            - spring-cloud-boot-admin
            - spring-cloud-eureka
        restart: unless-stopped           
                               
    loadbalancer:
        image: "${HAPROXY_IMAGE:-dockercloud/haproxy:latest}"
        #image: "${HAPROXY_IMAGE:-localhost:5083/haproxy:latest}"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8081:80
        depends_on:
            - spring-cloud-microservice
        links:
            - spring-cloud-microservice
        restart: unless-stopped d        
            
    spring-cloud-api-gateway:
        build:
            context: ./spring-cloud-api-gateway
            dockerfile: Dockerfile
        image: spring-cloud-api-gateway:latest
        environment:
            - VM_PARAMS=
                -Xms64m
                -Xmx256m
                -DEUREKA_SERVER=http://spring-cloud-eureka:8761/eureka
                -DADMIN_SERVER=http://spring-cloud-boot-admin:9000
                -DENABLE_EUREKA=true
                -DMICRO_SERVICE=loadbalancer:80
        ports:
            - 8082:9999               
        depends_on:
            - spring-cloud-boot-admin
            - spring-cloud-eureka
            - spring-cloud-microservice
            - loadbalancer
        restart: unless-stopped d                


# localhost im Docker-Netz finden:
# ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1;


#image: localhost:5000/spring-cloud-microservice:latest
#restart: always
        

# https://docs.docker.com/compose/compose-file/#resources                    
#         deploy:
#             resources:
#                 reservations:
#                     cpus: "0.5"
#                     memory: 128M
#                 limits:
#                     cpus: "1"
#                     memory: 256M

                    
#         environment:
#             SPRING_APPLICATION_JSON:
#                 '{
#         "eureka":
#         {
#           "client":
#           {
#             "serviceUrl":
#             {
#               "defaultZone": "http://eureka:9001/eureka"
#             }
#           },
#           "instance":
#           {
#             "preferIpAddress": "true"
#           }
#         },
#         "spring":
#         {
#           "boot":
#           {
#             "admin":
#             {
#               "client":
#               {
#                 "instance":
#                 {
#                   "prefer-ip": "true"
#                 },   
#                 "url": "http://admin:9000"
#               }
#             }
#           }
#         }
#         }'