# =================================================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================================================


# =================================================================================================
# Application Properties


# =================================================================================================
# Spring Properties
debug: false

spring:
  banner:
    charset: UTF-8
    web-environment: true
    web-application-type: SERVLET
  http:
    encoding:
      enabled: true
      charset: UTF-8
  jmx:
    enabled: false
  main:
    banner-mode: CONSOLE
  mvc:
    locale: de_DE
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: DETECT

# =================================================================================================
# Server Properties
server:
  compression:
    enabled: false
  error:
    whitelabel:
      enabled: true
  port: 8081
  servlet:
    context-path: /auth
    session:
      timeout: 30
  ssl:
    enabled: false
