# =================================================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# =================================================================================================


# =================================================================================================
# Application Properties


# =================================================================================================
# Spring Properties
logging:
  level:
    org.springframework: INFO


# =================================================================================================
# Server Properties
server:
  port: 8081
  servlet:
    context-path: /auth


