# PODs und Anzahl definieren
# kubectl apply -f deployment.yml;
# kubectl get pod;
# kubectl get deployment;
# kubectl describe pod microservice;
# kubectl describe deployment microservice;
# kubectl delete deployment microservice;
#
# eval $(minikube docker-env)
# minikube image load microservice:latest
# kubectl run microservice --image=microservice:latest --port=8989 --image-pull-policy=Never
# minikube image ls --format table
apiVersion: apps/v1
kind: Deployment
metadata:
    name: microservice
    labels:
        app: microservice
spec:
    selector:
        matchLabels:
            app: microservice
    replicas: 1
    template:
        metadata:
            name: microservice
            labels:
                app: microservice
        spec:
            containers:
                -   name: microservice
                    image: microservice:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 8080

#imagePullPolicy: IfNotPresent, Never
