# Define PODs and Replicas for microservice.
apiVersion: apps/v1
kind: Deployment
metadata:
    name: microservice
    labels:
        app: microservice
        env: test
spec:
    selector:
        matchLabels:
            app: microservice
            env: test
    replicas: 3
    template:
        metadata:
            name: microservice
            labels:
                app: microservice
                env: test
        spec:
            containers:
                -   name: microservice
                    image: 192.168.155.100:5000/microservice:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 8080
                            protocol: TCP
                    resources:
                        requests:
                            cpu: "10m"
                            memory: 64Mi
                        limits:
                            cpu: 0.75
                            memory: 128Mi
