# Service: External access.
# curl http://$(minikube service microservice --url)
apiVersion: v1
kind: Service
metadata:
    name: microservice
    labels:
        app: microservice
        env: test
spec:
    selector:
        app: microservice
        env: test
    ports:
        -   port: 8080
            targetPort: 8080
            protocol: TCP
    #type: NodePort
    type: LoadBalancer
