# PODs und Anzahl definieren
# kubectl apply -f deployment.yml;
# kubectl get pod;
# kubectl get deployment;
# kubectl describe pod microservice;
# kubectl describe deployment microservice;
# kubectl delete deployment microservice;
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    run: microservice   
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 3
  minReadySeconds: 30
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      name: microservice
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: mymicroservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080        
        env:
          - name: KEY
            value: "VALUE"        


   