/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model.tables;


import de.spring.jooq.model.Public;
import de.spring.jooq.model.tables.records.OrderItemRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItem extends TableImpl<OrderItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.ORDER_ITEM</code>
     */
    public static final OrderItem ORDER_ITEM = new OrderItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderItemRecord> getRecordType() {
        return OrderItemRecord.class;
    }

    /**
     * The column <code>PUBLIC.ORDER_ITEM.ID</code>.
     */
    public final TableField<OrderItemRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORDER_ITEM.ORDER_ID</code>.
     */
    public final TableField<OrderItemRecord, Long> ORDER_ID = createField(DSL.name("ORDER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORDER_ITEM.POSITION_NO</code>.
     */
    public final TableField<OrderItemRecord, Integer> POSITION_NO = createField(DSL.name("POSITION_NO"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORDER_ITEM.PRODUCT_CODE</code>.
     */
    public final TableField<OrderItemRecord, String> PRODUCT_CODE = createField(DSL.name("PRODUCT_CODE"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORDER_ITEM.QUANTITY</code>.
     */
    public final TableField<OrderItemRecord, Integer> QUANTITY = createField(DSL.name("QUANTITY"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORDER_ITEM.UNIT_PRICE</code>.
     */
    public final TableField<OrderItemRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("UNIT_PRICE"), SQLDataType.DECIMAL(12, 2).nullable(false), this, "");

    private OrderItem(Name alias, Table<OrderItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrderItem(Name alias, Table<OrderItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.ORDER_ITEM</code> table reference
     */
    public OrderItem(String alias) {
        this(DSL.name(alias), ORDER_ITEM);
    }

    /**
     * Create an aliased <code>PUBLIC.ORDER_ITEM</code> table reference
     */
    public OrderItem(Name alias) {
        this(alias, ORDER_ITEM);
    }

    /**
     * Create a <code>PUBLIC.ORDER_ITEM</code> table reference
     */
    public OrderItem() {
        this(DSL.name("ORDER_ITEM"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrderItemRecord> getPrimaryKey() {
        return Internal.createUniqueKey(OrderItem.ORDER_ITEM, DSL.name("CONSTRAINT_4"), new TableField[] { OrderItem.ORDER_ITEM.ID }, true);
    }

    @Override
    public List<Check<OrderItemRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("CONSTRAINT_4B"), "\"QUANTITY\" > 0", true),
            Internal.createCheck(this, DSL.name("CONSTRAINT_4BB"), "\"UNIT_PRICE\" >= CAST(0 AS NUMERIC(1))", true)
        );
    }

    @Override
    public OrderItem as(String alias) {
        return new OrderItem(DSL.name(alias), this);
    }

    @Override
    public OrderItem as(Name alias) {
        return new OrderItem(alias, this);
    }

    @Override
    public OrderItem as(Table<?> alias) {
        return new OrderItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItem rename(String name) {
        return new OrderItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItem rename(Name name) {
        return new OrderItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItem rename(Table<?> name) {
        return new OrderItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Condition condition) {
        return new OrderItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
