# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

artemis:
    broker-url: vm://0
    #broker-url: tcp://localhost:61616

logging:
    level:
        root: INFO
        org.apache.activemq: ERROR
        org.apache.activemq.artemis.core.server: INFO
        org.springframework: INFO
