# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

#tcp://192.168.1.210:9876
#vm://localhost?broker.persistent=false
#vm://embedded?broker.persistent=false,useShutdownHook=false

spring:
   activemq:
      broker-url: vm://embedded?broker.persistent=false,useShutdownHook=true
      #user:
      #password: 
      in-memory: true
      pool:
         enabled: false
         max-connections: 10

