/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model.tables.records;


import de.spring.jooq.model.tables.Customer;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Table for Customers
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CUSTOMER.ID</code>. PrimaryKey
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.ID</code>. PrimaryKey
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.CUSTOMER_NO</code>. Number of Customer
     */
    public void setCustomerNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.CUSTOMER_NO</code>. Number of Customer
     */
    public String getCustomerNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.NAME</code>. Name of Customer
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.NAME</code>. Name of Customer
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.EMAIL</code>. Mail of Customer
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.EMAIL</code>. Mail of Customer
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER.CREATED_AT</code>. Creation Timestamp of
     * Customer
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER.CREATED_AT</code>. Creation Timestamp of
     * Customer
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Long id, String customerNo, String name, String email, LocalDateTime createdAt) {
        super(Customer.CUSTOMER);

        setId(id);
        setCustomerNo(customerNo);
        setName(name);
        setEmail(email);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
