/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model.tables.records;


import de.spring.jooq.model.tables.OrderItem;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItemRecord extends UpdatableRecordImpl<OrderItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ORDER_ITEM.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_ITEM.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_ITEM.ORDER_ID</code>.
     */
    public void setOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_ITEM.ORDER_ID</code>.
     */
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_ITEM.POSITION_NO</code>.
     */
    public void setPositionNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_ITEM.POSITION_NO</code>.
     */
    public Integer getPositionNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_ITEM.PRODUCT_CODE</code>.
     */
    public void setProductCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_ITEM.PRODUCT_CODE</code>.
     */
    public String getProductCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_ITEM.QUANTITY</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_ITEM.QUANTITY</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_ITEM.UNIT_PRICE</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_ITEM.UNIT_PRICE</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemRecord
     */
    public OrderItemRecord() {
        super(OrderItem.ORDER_ITEM);
    }

    /**
     * Create a detached, initialised OrderItemRecord
     */
    public OrderItemRecord(Long id, Long orderId, Integer positionNo, String productCode, Integer quantity, BigDecimal unitPrice) {
        super(OrderItem.ORDER_ITEM);

        setId(id);
        setOrderId(orderId);
        setPositionNo(positionNo);
        setProductCode(productCode);
        setQuantity(quantity);
        setUnitPrice(unitPrice);
        resetChangedOnNotNull();
    }
}
