/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model.tables.records;


import de.spring.jooq.model.tables.Orders;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ORDERS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.ORDER_NO</code>.
     */
    public void setOrderNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.ORDER_NO</code>.
     */
    public String getOrderNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.ORDER_DATE</code>.
     */
    public void setOrderDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.ORDER_DATE</code>.
     */
    public LocalDate getOrderDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.STATUS</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Long id, Long customerId, String orderNo, LocalDate orderDate, String status) {
        super(Orders.ORDERS);

        setId(id);
        setCustomerId(customerId);
        setOrderNo(orderNo);
        setOrderDate(orderDate);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
