# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

server:
  port: 9999
  #servlet:
    #context-path: /

spring:
   jmx:
      enabled: false
   ldap:
      embedded:
         credential:
            username: uid=ben,ou=people
            password: benspassword
         base-dn: dc=springframework,dc=org
         ldif: classpath:test-server.ldif         
         port: 8389
         validation:
            enabled: false
            schema: file:/usr/share/evolution-data-server/evolutionperson.schema  
   main:
      allow-bean-definition-overriding: false
      web-application-type: SERVLET
       
