# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
debug: false

logging:
    level:
        root: INFO
        org.springframework.core.LocalVariableTableParameterNameDiscoverer: OFF

# Is spring-boot-starter-parent the Parent-POM, Resource-Delimiter is @.
info:
    app:
        name: ${project_artifactId}
        description: ${project_description}
        version: ${project_version}

server:
    error:
        whitelabel:
            enabled: true
    port: 8088
    servlet:
        context-path: /${project_artifactId}
        encoding:
            enabled: true
            charset: UTF-8
    shutdown: "graceful"

spring:
    output:
        ansi:
            enabled: ALWAYS

#<form action="http://localhost:8088/spring-web/actuator/shutdown" method="post" id="form_shutdown">
#<form action="shutdown" method="post" id="form_shutdown">
#   <button type="submit">System shutdown</button>
#</form>
# curl -X POST HOST:PORT/shutdown
# view-source:http://localhost:8088/spring-web/actuator/info
# view-source:http://localhost:8088/spring-web/actuator/health
# view-source:http://localhost:8088/spring-web/actuator/metrics
management:
    #    server:
    #        port: 8089
    endpoints:
        access:
            default: NONE
        web:
            base-path: /actuator
            exposure:
                #include: "*"
                include: health, info, metrics, shutdown
    endpoint:
        health:
            access: READ_ONLY
            show-details: ALWAYS
        info:
            access: READ_ONLY
        metrics:
            access: READ_ONLY
        shutdown:
            access: UNRESTRICTED
    info:
        defaults:
            enabled: true
        env:
            enabled: true
    health:
        defaults:
            enabled: true

---

spring:
    config:
        activate:
            on-profile: shutdown

logging:
    level:
        org.springframework.beans.factory.config.YamlPropertiesFactoryBean: INFO
