spring:
   main:  
      web-application-type: NONE
   jmx:
      enabled: false    
    
security:
   basic:
      enabled: false
   oauth2:
      client:
         clientId: my-client-id-read
         clientSecret: 'my-secret'
         accessTokenUri: http://localhost:8081/auth/oauth/token
         tokenName: access_token
         userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
         #authenticationScheme: header
         #clientAuthenticationScheme: header      
      #resource:
         #userInfoUri: http://localhost:8081/auth/rest/me
     