spring:
  main:  
    web-application-type: NONE
    
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: my-client-id
      clientSecret: '{noop}secret'
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      authenticationScheme: header
      clientAuthenticationScheme: header      
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
     