global:
    scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
scrape_configs:
    #    -   job_name: 'prometheus'
    #        static_configs:
    #            -   targets: [ '127.0.0.1:9090' ]

    -   job_name: 'spring-resilience'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
            -   targets: [ '192.168.155.100:8080' ]
