# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

info:
    app:
        description: ${project.description}
        name: ${project.artifactId}
        version: ${project.version}

logging:
    #  config: classpath:logback.xml
    #  level:
    #    root: INFO
    #    org.springframework: INFO
    pattern:
        console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS

server:
    port: 8081
    #servlet:
    #context-path: /

spring:
    main:
        banner-mode: 'OFF'
    output:
        ansi:
            enabled: DETECT   
