/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model;


import de.spring.jooq.model.tables.Customer;
import de.spring.jooq.model.tables.OrderItem;
import de.spring.jooq.model.tables.Orders;

import java.util.Arrays;
import java.util.List;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Table for Customers
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.ORDER_ITEM</code>.
     */
    public final OrderItem ORDER_ITEM = OrderItem.ORDER_ITEM;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.CUSTOMER_SEQ,
            Sequences.ORDER_ITEM_SEQ,
            Sequences.ORDERS_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Customer.CUSTOMER,
            OrderItem.ORDER_ITEM,
            Orders.ORDERS
        );
    }
}
