/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.CUSTOMER_SEQ</code>
     */
    public static final Sequence<Long> CUSTOMER_SEQ = Internal.createSequence("CUSTOMER_SEQ", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>PUBLIC.ORDER_ITEM_SEQ</code>
     */
    public static final Sequence<Long> ORDER_ITEM_SEQ = Internal.createSequence("ORDER_ITEM_SEQ", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>PUBLIC.ORDERS_SEQ</code>
     */
    public static final Sequence<Long> ORDERS_SEQ = Internal.createSequence("ORDERS_SEQ", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null);
}
