/*
 * This file is generated by jOOQ.
 */
package de.spring.jooq.model;


import de.spring.jooq.model.tables.Customer;
import de.spring.jooq.model.tables.OrderItem;
import de.spring.jooq.model.tables.Orders;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Table for Customers
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.ORDER_ITEM</code>.
     */
    public static final OrderItem ORDER_ITEM = OrderItem.ORDER_ITEM;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;
}
